### ISSUE TITLE
`describe` no longer returns the git tag in git-repository v0.22.1

### ISSUE THREAD

**Issue by davidkna** [Byron/gitoxide#503] opened 2022-08-26 17:16 UTC
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Tests that rely on the git tag in starship started failing with v0.22.1:

https://github.com/davidkna/starship/runs/8041122928?check_suite_focus=true

### Expected behavior 🤔

Return git tags for the current commit, like in previous versions.

### Steps to reproduce 🕹

https://github.com/davidkna/starship/blob/dependabot/cargo/git-repository-0.22.1/src/modules/git_commit.rs#L53-L67

**Comment by Byron** [comment] 2022-08-27 01:43
Thanks a lot the context and apologies for the regression! The fix is in `main` along with a test that could trigger it, and I validated it against `starship`. https://github.com/starship/starship/pull/4319 was created in the process to finish the upgrade.

I am closing this as the original issue is fixed and will follow up on all issues that might occour in the PR.

----

As a note, when running the `starship` tests locally even with 0.22.1 from crates.io, I was unable to reproduce the issue. I might have made a mistake somewhere, even though I am reasonably sure the tests didn't run against my local clone of `gitoxide`.

**Closed by Byron** 2022-08-27 01:43 UTC
