### ISSUE TITLE
Error with building gitoxide 0.8

### ISSUE THREAD

**Issue by roland-rollo** [Byron/gitoxide#159] opened 2021-08-15 06:46 UTC
I didn't have problem with installing 0.7 version, but when I wanted upgrade today, I saw this:
```
  Installing gitoxide v0.8.0
   Compiling libc v0.2.99
   Compiling version_check v0.9.3
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.28
   Compiling autocfg v1.0.1
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.74
   Compiling serde_derive v1.0.127
   Compiling serde v1.0.127
   Compiling lazy_static v1.4.0
   Compiling cc v1.0.69
   Compiling memchr v2.4.0
   Compiling scopeguard v1.1.0
   Compiling log v0.4.14
   Compiling pkg-config v0.3.19
   Compiling futures-core v0.3.16
   Compiling once_cell v1.8.0
   Compiling crossbeam-utils v0.8.5
   Compiling signal-hook v0.3.9
   Compiling quick-error v2.0.1
   Compiling regex-automata v0.1.10
   Compiling crossbeam-epoch v0.9.5
   Compiling typenum v1.13.0
   Compiling unicode-width v0.1.8
   Compiling bitflags v1.3.1
   Compiling proc-macro-hack v0.5.19
   Compiling radium v0.5.3
   Compiling fastrand v1.5.0
   Compiling cache-padded v1.1.1
   Compiling hex v0.4.3
   Compiling rayon-core v1.9.1
   Compiling pin-project-lite v0.2.7
   Compiling futures-io v0.3.16
   Compiling funty v1.1.0
   Compiling parking v2.0.0
   Compiling futures-channel v0.3.16
   Compiling crossbeam-queue v0.3.2
   Compiling waker-fn v1.1.0
   Compiling wyz v0.2.0
   Compiling unicode-segmentation v1.8.0
   Compiling cassowary v0.3.0
   Compiling const_fn v0.4.8
   Compiling tap v1.0.1
   Compiling crc32fast v1.2.1
   Compiling futures-sink v0.3.16
   Compiling event-listener v2.5.1
   Compiling either v1.6.1
   Compiling ansi_term v0.12.1
   Compiling adler v1.0.2
   Compiling humantime v2.1.0
   Compiling slab v0.4.4
   Compiling cpufeatures v0.1.5
   Compiling human_format v1.0.3
   Compiling ppv-lite86 v0.2.10
   Compiling itoa v0.4.7
   Compiling opaque-debug v0.3.0
   Compiling same-file v1.0.6
   Compiling bytesize v1.1.0
   Compiling bytes v1.0.1
   Compiling sha1 v0.6.0
   Compiling tinyvec_macros v0.1.0
   Compiling remove_dir_all v0.5.3
   Compiling matches v0.1.9
   Compiling unicode-bidi v0.3.6
   Compiling percent-encoding v2.1.0
   Compiling curl v0.4.38
   Compiling byteorder v1.4.3
   Compiling arrayvec v0.7.1
   Compiling home v0.5.3
   Compiling openssl-probe v0.1.4
   Compiling ryu v1.0.5
   Compiling base64 v0.13.0
   Compiling anyhow v1.0.43
   Compiling os_str_bytes v3.1.0
   Compiling serde_json v1.0.66
   Compiling termcolor v1.1.2
   Compiling vec_map v0.8.2
   Compiling strsim v0.10.0
   Compiling os_str_bytes v2.4.0
   Compiling fs-err v2.6.0
   Compiling instant v0.1.10
   Compiling lock_api v0.4.4
   Compiling textwrap v0.12.1
   Compiling standback v0.2.17
   Compiling generic-array v0.14.4
   Compiling nom v6.1.2
   Compiling time v0.2.22
   Compiling ahash v0.7.4
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling concurrent-queue v1.2.2
   Compiling memoffset v0.6.4
   Compiling num-traits v0.2.14
   Compiling miniz_oxide v0.4.4
   Compiling rayon v1.5.1
   Compiling indexmap v1.7.0
   Compiling cmake v0.1.45
   Compiling openssl-src v111.15.0+1.1.1k
   Compiling itertools v0.10.1
   Compiling walkdir v2.3.2
   Compiling tinyvec v1.3.1
   Compiling form_urlencoded v1.0.1
   Compiling uluru v2.2.0
   Compiling sha1-asm v0.5.1
   Compiling curl-sys v0.4.45+curl-7.78.0
   Compiling heck v0.3.3
   Compiling openssl-sys v0.9.65
   Compiling async-channel v1.6.1
   Compiling libz-sys v1.1.3
   Compiling crossbeam-channel v0.5.1
   Compiling futures-lite v1.12.0
   Compiling bitvec v0.19.5
   Compiling quote v1.0.9
   Compiling signal-hook-registry v1.4.0
   Compiling getrandom v0.2.3
   Compiling num_cpus v1.13.0
   Compiling mio v0.7.13
   Compiling atty v0.2.14
   Compiling socket2 v0.4.1
   Compiling polling v2.1.0
   Compiling filebuffer v0.4.0
   Compiling unicode-normalization v0.1.19
   Compiling env_logger v0.9.0
   Compiling rand_core v0.6.3
   Compiling dashmap v4.0.2
   Compiling rand_chacha v0.3.1
   Compiling signal-hook-mio v0.2.1
   Compiling block-buffer v0.9.0
   Compiling digest v0.9.0
   Compiling async-io v1.6.0
   Compiling hashbrown v0.11.2
   Compiling crossbeam-deque v0.8.1
   Compiling btoi v0.4.2
   Compiling sha-1 v0.9.7
   Compiling idna v0.2.3
   Compiling rand v0.8.4
   Compiling crossbeam v0.8.1
   Compiling lru v0.6.6
   Compiling memory-lru v0.1.0
   Compiling url v2.2.2
   Compiling tempfile v3.2.0
   Compiling git-tempfile v0.6.0
   Compiling git-lock v0.3.1
   Compiling git-config v0.1.3
   Compiling jwalk v0.6.0
   Compiling time-macros-impl v0.1.2
   Compiling thiserror-impl v1.0.26
   Compiling maybe-async v0.2.6
   Compiling clap_derive v3.0.0-beta.4
   Compiling flate2 v1.0.20
   Compiling time-macros v0.1.1
   Compiling thiserror v1.0.26
   Compiling clap v3.0.0-beta.2
   Compiling smallvec v1.6.1
   Compiling bstr v0.2.16
   Compiling git-hash v0.5.0
   Compiling parking_lot_core v0.8.3
   Compiling parking_lot v0.11.1
   Compiling git-validate v0.5.1
   Compiling git-actor v0.3.2
   Compiling git-url v0.3.2
   Compiling git-packetline v0.9.0
   Compiling crossterm v0.20.0
   Compiling git-object v0.12.1
   Compiling tui v0.16.0
   Compiling git-traverse v0.7.1
   Compiling git-diff v0.8.1
   Compiling tui-react v0.16.0
   Compiling crosstermion v0.8.1
   Compiling prodash v15.0.0
   Compiling git-features v0.16.1
   Compiling git-pack v0.8.1
   Compiling git-ref v0.5.2
   Compiling git-commitgraph v0.4.1
   Compiling git-odb v0.20.1
   Compiling git-transport v0.10.0
   Compiling git-protocol v0.8.1
   Compiling git-repository v0.7.1
   Compiling gitoxide-core v0.10.1
   Compiling gitoxide v0.8.0
error[E0433]: failed to resolve: could not find `Args` in `clap`
 --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:5:17
  |
5 | #[derive(Debug, Clap)]
  |                 ^^^^ could not find `Args` in `clap`
  |
  = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `into_app_for_update` is not a member of trait `clap::IntoApp`
 --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:5:17
  |
5 | #[derive(Debug, Clap)]
  |                 ^^^^ not a member of trait `clap::IntoApp`
  |
  = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `update_from_arg_matches` is not a member of trait `clap::FromArgMatches`
 --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:5:17
  |
5 | #[derive(Debug, Clap)]
  |                 ^^^^ not a member of trait `clap::FromArgMatches`
  |
  = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `into_app_for_update` is not a member of trait `clap::IntoApp`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:28:17
   |
28 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::IntoApp`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `update_from_arg_matches` is not a member of trait `clap::FromArgMatches`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:28:17
   |
28 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::FromArgMatches`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `Args` in `clap`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:42:11
   |
42 |     Tools(ToolCommands),
   |           ^^^^^^^^^^^^ could not find `Args` in `clap`

error[E0407]: method `augment_subcommands_for_update` is not a member of trait `clap::Subcommand`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:28:17
   |
28 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::Subcommand`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `has_subcommand` is not a member of trait `clap::Subcommand`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:28:17
   |
28 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::Subcommand`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `into_app_for_update` is not a member of trait `clap::IntoApp`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:47:17
   |
47 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::IntoApp`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `update_from_arg_matches` is not a member of trait `clap::FromArgMatches`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:47:17
   |
47 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::FromArgMatches`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `Args` in `clap`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:76:19
   |
76 |     EstimateHours(EstimateHours),
   |                   ^^^^^^^^^^^^^ could not find `Args` in `clap`

error[E0407]: method `augment_subcommands_for_update` is not a member of trait `clap::Subcommand`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:47:17
   |
47 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::Subcommand`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `has_subcommand` is not a member of trait `clap::Subcommand`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:47:17
   |
47 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::Subcommand`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `Args` in `clap`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:79:17
   |
79 | #[derive(Debug, Clap)]
   |                 ^^^^ could not find `Args` in `clap`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `into_app_for_update` is not a member of trait `clap::IntoApp`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:79:17
   |
79 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::IntoApp`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `update_from_arg_matches` is not a member of trait `clap::FromArgMatches`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:79:17
   |
79 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::FromArgMatches`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0576]: cannot find method or associated constant `update_from_arg_matches` in trait `clap::FromArgMatches`
   --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:25:14
    |
25  |     pub cmd: Subcommands,
    |              ^^^^^^^^^^^ help: an associated function with a similar name exists: `from_arg_matches`
    |
   ::: /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.2/src/derive.rs:156:5
    |
156 |     fn from_arg_matches(matches: &ArgMatches) -> Self;
    |     -------------------------------------------------- similarly named associated function `from_arg_matches` defined here

error[E0404]: expected trait, found derive macro `clap::Args`
 --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:5:17
  |
5 | #[derive(Debug, Clap)]
  |                 ^^^^ not a trait
  |
  = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0576]: cannot find method or associated constant `augment_subcommands_for_update` in trait `clap::Subcommand`
 --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:5:17
  |
5 | #[derive(Debug, Clap)]
  |                 ^^^^ not found in `clap::Subcommand`
  |
  = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0576]: cannot find method or associated constant `augment_subcommands_for_update` in trait `clap::Subcommand`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:28:17
   |
28 | #[derive(Debug, Clap)]
   |                 ^^^^ not found in `clap::Subcommand`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0576]: cannot find method or associated constant `augment_subcommands_for_update` in trait `clap::Subcommand`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:47:17
   |
47 | #[derive(Debug, Clap)]
   |                 ^^^^ not found in `clap::Subcommand`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0404]: expected trait, found derive macro `clap::Args`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/porcelain/options.rs:79:17
   |
79 | #[derive(Debug, Clap)]
   |                 ^^^^ not a trait
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 22 previous errors

Some errors have detailed explanations: E0404, E0407, E0433, E0576.
For more information about an error, try `rustc --explain E0404`.
error: could not compile `gitoxide`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0433]: failed to resolve: could not find `Args` in `clap`
 --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/plumbing/pretty/options.rs:6:17
  |
6 | #[derive(Debug, Clap)]
  |                 ^^^^ could not find `Args` in `clap`
  |
  = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `into_app_for_update` is not a member of trait `clap::IntoApp`
 --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/plumbing/pretty/options.rs:6:17
  |
6 | #[derive(Debug, Clap)]
  |                 ^^^^ not a member of trait `clap::IntoApp`
  |
  = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `update_from_arg_matches` is not a member of trait `clap::FromArgMatches`
 --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/plumbing/pretty/options.rs:6:17
  |
6 | #[derive(Debug, Clap)]
  |                 ^^^^ not a member of trait `clap::FromArgMatches`
  |
  = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `into_app_for_update` is not a member of trait `clap::IntoApp`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/plumbing/pretty/options.rs:44:17
   |
44 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::IntoApp`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `update_from_arg_matches` is not a member of trait `clap::FromArgMatches`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/plumbing/pretty/options.rs:44:17
   |
44 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::FromArgMatches`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `augment_subcommands_for_update` is not a member of trait `clap::Subcommand`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/plumbing/pretty/options.rs:44:17
   |
44 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::Subcommand`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `has_subcommand` is not a member of trait `clap::Subcommand`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/plumbing/pretty/options.rs:44:17
   |
44 | #[derive(Debug, Clap)]
   |                 ^^^^ not a member of trait `clap::Subcommand`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0576]: cannot find method or associated constant `update_from_arg_matches` in trait `clap::FromArgMatches`
   --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/plumbing/pretty/options.rs:41:14
    |
41  |     pub cmd: Subcommands,
    |              ^^^^^^^^^^^ help: an associated function with a similar name exists: `from_arg_matches`
    |
   ::: /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.2/src/derive.rs:156:5
    |
156 |     fn from_arg_matches(matches: &ArgMatches) -> Self;
    |     -------------------------------------------------- similarly named associated function `from_arg_matches` defined here

error[E0404]: expected trait, found derive macro `clap::Args`
 --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/plumbing/pretty/options.rs:6:17
  |
6 | #[derive(Debug, Clap)]
  |                 ^^^^ not a trait
  |
  = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0576]: cannot find method or associated constant `augment_subcommands_for_update` in trait `clap::Subcommand`
 --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/plumbing/pretty/options.rs:6:17
  |
6 | #[derive(Debug, Clap)]
  |                 ^^^^ not found in `clap::Subcommand`
  |
  = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0576]: cannot find method or associated constant `augment_subcommands_for_update` in trait `clap::Subcommand`
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/gitoxide-0.8.0/src/plumbing/pretty/options.rs:44:17
   |
44 | #[derive(Debug, Clap)]
   |                 ^^^^ not found in `clap::Subcommand`
   |
   = note: this error originates in the derive macro `Clap` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 11 previous errors

Some errors have detailed explanations: E0404, E0407, E0433, E0576.
For more information about an error, try `rustc --explain E0404`.
error: failed to compile `gitoxide v0.8.0`, intermediate artifacts can be found at `/tmp/cargo-install0BUdcQ`

Caused by:
  build failed
```

I use Arch Linux, but don't see in repositories or AUR, clap package.

**Comment by edward-shen** [comment] 2021-08-15 06:54
Looks like it's compiling clap 3.0.0-beta.2 while using clap_derive 3.0.0-beta.4, that might be a reason for the compile issues.

Are we pinning the version to beta.2 anywhere? Iirc cargo should should use the latest beta version.

**Comment by Byron** [comment] 2021-08-15 07:17
Sorry for that, CI noticed it a while ago and I believe to have fixed it, but forgot to push. Time to auto-push with `cargo git-smart-release`.

It's interesting that reproducible builds won't work with .BETAs or .RC releases as semantic version says it's OK to upgrade then, even though most often it's not. The only way to get reproducible builds would be to consistently pin the version of these.

I unpinned the version now and creating a new patch release, hoping to fix the issue until .BETA 5 breaks it again ;).

**Comment by Byron** [comment] 2021-08-15 08:45
This is fixed now but will break again once the next beta arrives.

**Closed by Byron** 2021-08-15 08:45 UTC

**Comment by roland-rollo** [comment] 2021-08-15 11:12
Thank you!
