### ISSUE TITLE
cargo-smart-release fails to install

### ISSUE THREAD

**Issue by Alxandr** [Byron/gitoxide#204] opened 2021-09-20 14:19 UTC
I tried to install `cargo-smart-release` on nightly on ubuntu (WSL2), and got multiple compile errors:

![image](https://user-images.githubusercontent.com/112334/134018271-32b1db35-30b4-43e2-b719-466d77874636.png)

![image](https://user-images.githubusercontent.com/112334/134018329-3486c1e0-0090-4d4b-8044-d98526c35199.png)

**Comment by Byron** [comment] 2021-09-20 14:21
Thanks for reporting. Which command was used for installation?

**Comment by Alxandr** [comment] 2021-09-20 14:26
`cargo install cargo-smart-release`

**Comment by Alxandr** [comment] 2021-09-20 14:29
In case it's usefull:

[![asciicast](https://asciinema.org/a/436895.svg)](https://asciinema.org/a/436895)

**Comment by Byron** [comment] 2021-09-20 14:34
Thanks a lot, that should be easily reproducible. Definitely time to test installation on CI once this is fixed 😅

**Comment by Alxandr** [comment] 2021-09-20 14:39
Yeah, I guess this is one of the downsides for "install" to be a "download sources and compile" as opposed to "download binary".

**Comment by Byron** [comment] 2021-09-20 14:58
Since a fix will probably have to wait till v0.4 (WIP) installing from git should be working.

`cargo install —git https://github.com/Byron/gitoxide —package cargo-smart-release —bin cargo-smart-release` should do the trick.

**Comment by asaaki** [comment] 2021-10-03 12:44
`cargo` doesn't like the `--package` argument, but the following shorter version works:

```sh
cargo install --git https://github.com/Byron/gitoxide cargo-smart-release
```

**Comment by Byron** [comment] 2021-10-11 00:32
Sorry, the closing happened by accident.

**Comment by Byron** [comment] 2021-10-15 10:02
It keeps being closed automatically.

Now at least the new release is available so this issue should be fixed: https://crates.io/crates/cargo-smart-release/0.4.0

**Closed by Byron** 2021-10-15 10:02 UTC

**Comment by asaaki** [comment] 2021-10-16 10:04
Can confirm from my side, Ubuntu (WSL2) and Win10 install it fine now. Thanks for the fix and release! ❤️
