### ISSUE TITLE
0.37.0 introduced code that isn't stable with 1.64

### ISSUE THREAD

**Issue by CraZySacX** [Byron/gitoxide#750] opened 2023-02-20 21:30 UTC
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

When compiling with 1.64 I get the following error:

> error[E0658]: `let...else` statements are unstable
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gix-0.37.0/src/object/tree/diff/for_each.rs:135:9
    |
135 | /         let Some(tracked) = self.tracked.as_mut() else {
136 | |             return Ok(None)
137 | |         };
    | |__________^
    |
    = note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information

I dug a bit into the RFC and it appears this became stable in 1.65.    You may just want to bump the MSRV to 1.65.

### Expected behavior 🤔

Well, if you wish to keep 1.64 as the MSRV this would need to compile against it.

**Comment by Byron** [comment] 2023-02-21 07:12
Thanks for reporting!

After investigating this it turned out that CI didn't catch it because:

* the `rust-toolchain.toml` file caused an auto-download of the rustc version configured there, which was 1.65. The pipeline didn't actually test what I thought it would.
* the job was configured to continue on error due to some other issue in the dependency tree which by now was fixed.

This is why the problem shouldn't occour again.

I also published a new patch release with the fix: 0.37.2.

Closing as the issue is provably fixed.

**Closed by Byron** 2023-02-21 07:12 UTC
