### ISSUE TITLE
Panic when cloning empty repo

### ISSUE THREAD

**Issue by jalil-salame** [Byron/gitoxide#792] opened 2023-03-26 14:37 UTC
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

When cloning an empty repo `gix` panics:

```console
$ gix clone $my-empty-repo-rul
thread 'main' panicked at 'internal error: entered unreachable code: clone always has changes', /usr/src/debug/gitoxide/gitoxide-0.23.0/gitoxide-core/src/repository/clone.rs:87:17===   ===   ===   ===   ===   ===]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior 🤔

Copy `git`'s behaviour and only display a warning:

```console
$ git clone $my-empty-repo-url
Cloning into 'empty-repo'...
warning: You appear to have cloned an empty repository.
```

### Steps to reproduce 🕹

1. Create an empty GH repo
2. Clone it with `git` and see a warning.
3. Delete folder.
4. Clone it with `gix` and see a panic.

**Comment by Byron** [comment] 2023-03-27 07:47
Thanks a lot, the issue is now fixed in `main`.

**Closed by Byron** 2023-03-27 07:47 UTC
