### ISSUE TITLE
2 repository::worktree tests fail for me

### ISSUE THREAD

**Issue by ultrasaurus** [Byron/gitoxide#488] opened 2022-08-20 00:48 UTC
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

`make tests` reports two failures

```
---- repository::worktree::from_nonbare_parent_repo stdout ----
StaticLinkedList<64>[7fdead80a828]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeac01b628]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeae02a628]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdead00cc28]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeac016e28]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeae00ac28]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdead810c28]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeaf00da28]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeaf00ea28]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdead80e028]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeae00ca28]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeae03d228]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeb000b828]: 0 / 0 (hits/misses) = NaN%, puts = 0
thread 'repository::worktree::from_nonbare_parent_repo' panicked at 'assertion failed: `(left == right)`
  left: `Some("added with --lock")`,
 right: `None`', git-repository/tests/repository/worktree.rs:258:9
StaticLinkedList<64>[7fdead80c028]: 0 / 0 (hits/misses) = NaN%, puts = 0

---- repository::worktree::from_bare_parent_repo stdout ----
StaticLinkedList<64>[7fdeac01b628]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeac01b628]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdead80da28]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdead020e28]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdead01e828]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeae03c828]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdead020628]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeaf009028]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeae03ea28]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdead809828]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeac01a028]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeae03d228]: 0 / 0 (hits/misses) = NaN%, puts = 0
StaticLinkedList<64>[7fdeae80e828]: 0 / 0 (hits/misses) = NaN%, puts = 0
thread 'repository::worktree::from_bare_parent_repo' panicked at 'assertion failed: `(left == right)`
  left: `Some("added with --lock")`,
 right: `None`', git-repository/tests/repository/worktree.rs:258:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
StaticLinkedList<64>[7fdeac043a28]: 0 / 0 (hits/misses) = NaN%, puts = 0
```

### Expected behavior 🤔

all tests should pass

### Steps to reproduce 🕹

I can re-run just the failing package with:
```
cargo test -p git-repository --test git-with-regex --features="regex"
```

I imagine this is something weird on my machine, since my tiny PR passed ci:  https://github.com/Byron/gitoxide/pull/487

in case it's helpful, here's my machine info:
```
uname -a
Darwin Airtemis.attlocal.net 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 x86_64 i386 MacBookAir10,1 Darwin
```

**Comment by Byron** [comment] 2022-08-20 02:15
Thanks for letting me know!

For reference, `gitoxide`'s test suite depends on the `git` command-line which is used to establish a baseline. On CI, there are two modes of operation: 'canned' and 'real' (I just made these up). The 'canned' mode just extracts git repositories from archives stored via `git-lfs` and never executes the `git` binary, which greatly speeds things up on windows for example. Some tests, however, leave absolute paths in these files and thus cannot be easily 'canned', and the failing test is one of them.

Thus it depends on the `git` binary on your system. 
You could definitely help me fix this like so:

```sh
git --version
# you probably want to truncate the absolute paths in there before posting
cat ./git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/worktree-list.baseline
```

My hypothesis is that the baseline it generates looks different from what it expects - it's produced by `git worktree list --porcelain` and maybe `git` produces a different format for some reason so it can't be parsed properly  by the test suite.

Here is how the baseline looks like for me:

```
worktree /Users/byron/dev/github.com/Byron/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/repo.git
bare

worktree /Users/byron/dev/github.com/Byron/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/prev/wt-a
HEAD 3dcc68215458b705fbbaeeeab886a7ed7b69143f
detached

worktree /Users/byron/dev/github.com/Byron/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/wt-a
HEAD f1fdf6d80d565c7c946a67b0f62430749e3c843e
branch refs/heads/wt-a

worktree /Users/byron/dev/github.com/Byron/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/wt-a/nested-wt-b
HEAD 3dcc68215458b705fbbaeeeab886a7ed7b69143f
detached

worktree /Users/byron/dev/github.com/Byron/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/wt-b
HEAD 3dcc68215458b705fbbaeeeab886a7ed7b69143f
detached

worktree /Users/byron/dev/github.com/Byron/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/wt-c-locked
HEAD f1fdf6d80d565c7c946a67b0f62430749e3c843e
branch refs/heads/wt-c-locked
locked added with --lock

worktree /Users/byron/dev/github.com/Byron/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/wt-deleted
HEAD f1fdf6d80d565c7c946a67b0f62430749e3c843e
branch refs/heads/wt-deleted
prunable gitdir file points to non-existent location
```

I have a hunch that the `locked <reason>` line is simply missing in yours or formatted differently.
Thanks for your help.

**Comment by Byron** [comment] 2022-08-20 03:03
I took the liberty to apply a fix for what I think the issue is and you can try agin on the latest `main` - this time it should work.

I also invite you to run `make nextest` for maximum carnage in terms of testing, maybe that can lure out more even more problems.

**Comment by ultrasaurus** [comment] 2022-08-20 04:23
```
git --version
git version 2.30.1 (Apple Git-130)
```

here's the (edited) output of `cat ./git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/worktree-list.baseline`
```
worktree /mypath/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/repo.git
bare

worktree /mypath/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/prev/wt-a
HEAD 3dcc68215458b705fbbaeeeab886a7ed7b69143f
detached

worktree /mypath/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/wt-a
HEAD f1fdf6d80d565c7c946a67b0f62430749e3c843e
branch refs/heads/wt-a

worktree /mypath/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/wt-a/nested-wt-b
HEAD 3dcc68215458b705fbbaeeeab886a7ed7b69143f
detached

worktree /mypath/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/wt-b
HEAD 3dcc68215458b705fbbaeeeab886a7ed7b69143f
detached

worktree /mypath/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/wt-c-locked
HEAD f1fdf6d80d565c7c946a67b0f62430749e3c843e
branch refs/heads/wt-c-locked

worktree /mypath/gitoxide/git-repository/tests/fixtures/generated-do-not-edit/make_worktree_repo/2636804440-unix/wt-deleted
HEAD f1fdf6d80d565c7c946a67b0f62430749e3c843e
branch refs/heads/wt-deleted

```

I'll pull your fix and try it out!

FYI -- I would also be ok with upgrading my version of git too :)

**Comment by ultrasaurus** [comment] 2022-08-20 04:26
checked out branch `version-check` and the tests pass -- nice!

running...
```
cargo test -p git-repository --test git-with-regex --features="regex"
```

result:
```
test result: ok. 72 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.11s
```

**Comment by Byron** [comment] 2022-08-20 04:31
> checked out branch version-check and the tests pass -- nice!

Thanks for compensating for me just running away from the computer without merging :D. Good to know that it does indeed work as intended.

> FYI -- I would also be ok with upgrading my version of git too :)

I am glad you didn't as there is now machinery to make the test suite more robust, I am loving it.

In any case, this issue seems fixed, closing.

**Closed by Byron** 2022-08-20 04:31 UTC
